DataDir =  "${CoverageControl_ws}/lpac/" # Absolute location

GPUs =  [0, 1]
NumWorkers = 4
# Directory to save the model
# If a model is already present, it will be loaded
# Similarly, for the optimizer
[LPACModel]
Dir = "${CoverageControl_ws}/lpac/models/"

[CNNModel]
Dir = "${CoverageControl_ws}/lpac/models/" # Absolute location
Model = "model.pt"
Optimizer = "optimizer.pt"

[ModelConfig]
UseCommMaps = true

[GNNBackBone]
InputDim = 7
NumHops = 3
NumLayers = 5
LatentSize = 256
OutputDim = 2

[LPACTraining]
LearningRate = 0.0001
WeightDecay = 0.001
BatchSize = 10
NumEpochs = 15

[CNNBackBone]
InputDim = 4
NumLayers = 3
LatentSize = 32
KernelSize = 3
ImageSize = 32
OutputDim = 7

[CNNTraining]
LearningRate = 0.0001
WeightDecay = 0.001
BatchSize = 10
NumEpochs = 15
Momentum = 0.1
