var searchData=
[
  ['c_20interface_0',['C++ Interface',['../quick_start.html#autotoc_md9',1,'']]],
  ['centralized_5fcvt_2eh_1',['centralized_cvt.h',['../centralized__cvt_8h.html',1,'']]],
  ['centralizedcvt_2',['CentralizedCVT',['../classCoverageControl_1_1CentralizedCVT.html',1,'CoverageControl']]],
  ['cgal_5fdelaunayhelper_3',['CGAL_DelaunayHelper',['../structCoverageControl_1_1CGAL__DelaunayHelper.html',1,'CoverageControl']]],
  ['challenge_4',['The Challenge',['../lpac.html#autotoc_md28',1,'']]],
  ['checkoscillation_5',['CheckOscillation',['../classCoverageControl_1_1CoverageSystem.html#a845b117e1f5170f6b13c29737f7b9c8a',1,'CoverageControl::CoverageSystem']]],
  ['citation_6',['Citation',['../index.html#autotoc_md2',1,'']]],
  ['clairvoyant_5fcvt_2eh_7',['clairvoyant_cvt.h',['../clairvoyant__cvt_8h.html',1,'']]],
  ['clairvoyantcvt_8',['ClairvoyantCVT',['../classCoverageControl_1_1ClairvoyantCVT.html',1,'CoverageControl']]],
  ['cnn_9',['CNN',['../classCoverageControlTorch_1_1models_1_1cnn_1_1CNN.html',1,'CoverageControlTorch::models::cnn']]],
  ['cnnbackbone_10',['CNNBackBone',['../classCoverageControlTorch_1_1models_1_1cnn__backbone_1_1CNNBackBone.html',1,'CoverageControlTorch::models::cnn_backbone']]],
  ['cnnconfigparser_11',['CNNConfigParser',['../classCoverageControlTorch_1_1models_1_1config__parser_1_1CNNConfigParser.html',1,'CoverageControlTorch::models::config_parser']]],
  ['cnngnn_12',['CNNGNN',['../classCoverageControlTorch_1_1models_1_1gnn_1_1CNNGNN.html',1,'CoverageControlTorch::models::gnn']]],
  ['cnngnndataset_13',['CNNGNNDataset',['../classCoverageControlTorch_1_1data__loaders_1_1data__loaders_1_1CNNGNNDataset.html',1,'CoverageControlTorch::data_loaders::data_loaders']]],
  ['communication_5fmaps_5f_14',['communication_maps_',['../classCoverageControl_1_1CoverageSystem.html#afa4755d09ceb9bfc1fb24859ee52aabc',1,'CoverageControl::CoverageSystem']]],
  ['computeactions_15',['ComputeActions',['../classCoverageControl_1_1AbstractController.html#af5bf5df992a8147d832f170e26a93e20',1,'CoverageControl::AbstractController::ComputeActions()'],['../classCoverageControl_1_1CentralizedCVT.html#a93324c1cb821ae58acecca65beda970f',1,'CoverageControl::CentralizedCVT::ComputeActions()'],['../classCoverageControl_1_1ClairvoyantCVT.html#a93324c1cb821ae58acecca65beda970f',1,'CoverageControl::ClairvoyantCVT::ComputeActions()'],['../classCoverageControl_1_1DecentralizedCVT.html#a93324c1cb821ae58acecca65beda970f',1,'CoverageControl::DecentralizedCVT::ComputeActions()'],['../classCoverageControl_1_1NearOptimalCVT.html#a93324c1cb821ae58acecca65beda970f',1,'CoverageControl::NearOptimalCVT::ComputeActions()'],['../classCoverageControl_1_1OracleBangExploreExploit.html#a93324c1cb821ae58acecca65beda970f',1,'CoverageControl::OracleBangExploreExploit::ComputeActions()'],['../classCoverageControl_1_1OracleExploreExploit.html#a93324c1cb821ae58acecca65beda970f',1,'CoverageControl::OracleExploreExploit::ComputeActions()']]],
  ['computeadjacencymatrix_16',['ComputeAdjacencyMatrix',['../classCoverageControl_1_1CoverageSystem.html#acff573c6715926291c234074b14965ae',1,'CoverageControl::CoverageSystem']]],
  ['computeimportancerectangle_17',['ComputeImportanceRectangle',['../classCoverageControl_1_1WorldIDF.html#af913a85adce2dc93045e8754c13d8ba0',1,'CoverageControl::WorldIDF']]],
  ['computeoffsets_18',['ComputeOffsets',['../namespaceCoverageControl_1_1MapUtils.html#a74ee1b41afab01261eb3d6b55bc074c3',1,'CoverageControl::MapUtils']]],
  ['config_2eh_19',['config.h',['../config_8h.html',1,'']]],
  ['constants_20',['Constants',['../group__cpp__api__constants.html',1,'']]],
  ['constants_2eh_21',['constants.h',['../constants_8h.html',1,'']]],
  ['container_22',['Docker Container',['../docker.html#autotoc_md18',1,'']]],
  ['contributors_23',['Contributors',['../index.html#autotoc_md5',1,'']]],
  ['control_24',['Decentralized Coverage Control',['../coverage-control-problem.html#autotoc_md15',1,'']]],
  ['core_20api_25',['Core API',['../group__cpp__api.html',1,'']]],
  ['core_20library_26',['Building the Core Library',['../installation-from-source.html#autotoc_md24',1,'']]],
  ['core_5fbinds_2eh_27',['core_binds.h',['../core__binds_8h.html',1,'']]],
  ['cosangle_28',['CosAngle',['../classCoverageControl_1_1Vec2d.html#af6b42489d9e9fb4eab25ec578239e7dc',1,'CoverageControl::Vec2d']]],
  ['cost_20function_29',['Cost Function',['../coverage-control-problem.html#autotoc_md11',1,'']]],
  ['coverage_20control_30',['Decentralized Coverage Control',['../coverage-control-problem.html#autotoc_md15',1,'']]],
  ['coverage_5falgorithm_2ecpp_31',['coverage_algorithm.cpp',['../coverage__algorithm_8cpp.html',1,'']]],
  ['coverage_5fsystem_2ecpp_32',['coverage_system.cpp',['../coverage__system_8cpp.html',1,'']]],
  ['coverage_5fsystem_2eh_33',['coverage_system.h',['../coverage__system_8h.html',1,'']]],
  ['coveragecontrol_34',['CoverageControl',['../namespaceCoverageControl.html',1,'']]],
  ['coveragecontrol_3a_3amaputils_35',['MapUtils',['../namespaceCoverageControl_1_1MapUtils.html',1,'CoverageControl']]],
  ['coveragesystem_36',['CoverageSystem',['../classCoverageControl_1_1CoverageSystem.html',1,'CoverageSystem'],['../classCoverageControl_1_1CoverageSystem.html#a6d0fb1a19ee057e5d274e1b8fc9f9ea5',1,'CoverageControl::CoverageSystem::CoverageSystem()=delete'],['../classCoverageControl_1_1CoverageSystem.html#aa488e07158f6e2d9a663d6eaa0fc0d4d',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params)'],['../classCoverageControl_1_1CoverageSystem.html#ad241f1f0e345c4c3df964dcbf8fd6dd6',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params, int const num_gaussians, int const num_robots)'],['../classCoverageControl_1_1CoverageSystem.html#ab371d481cd2055d5a61bb003fd3230f7',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params, WorldIDF const &amp;world_idf, std::string const &amp;pos_file_name)'],['../classCoverageControl_1_1CoverageSystem.html#ae7b8ae7f16a57e4d99aad33989b722c7',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params, WorldIDF const &amp;world_idf, std::vector&lt; Point2 &gt; const &amp;robot_positions)'],['../classCoverageControl_1_1CoverageSystem.html#a5becb78ce3932fe865407f7d566dd2f5',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params, std::vector&lt; BivariateNormalDistribution &gt; const &amp;dists, std::vector&lt; Point2 &gt; const &amp;robot_positions)']]],
  ['cuda_20support_20optional_20but_20recommended_20for_20gpu_20acceleration_37',['CUDA Support (Optional but recommended for GPU acceleration)',['../installation-from-source.html#autotoc_md22',1,'']]]
];
