var searchData=
[
  ['c_20interface_0',['C++ Interface',['../quick_start.html#autotoc_md23',1,'']]],
  ['centralized_5fcvt_2eh_1',['centralized_cvt.h',['../centralized__cvt_8h.html',1,'']]],
  ['centralizedcvt_2',['CentralizedCVT',['../classCoverageControl_1_1CentralizedCVT.html',1,'CoverageControl']]],
  ['cgal_5fdelaunayhelper_3',['CGAL_DelaunayHelper',['../structCoverageControl_1_1CGAL__DelaunayHelper.html',1,'CoverageControl']]],
  ['challenge_4',['The Challenge',['../lpac.html#autotoc_md32',1,'']]],
  ['checkoscillation_5',['CheckOscillation',['../classCoverageControl_1_1CoverageSystem.html#a845b117e1f5170f6b13c29737f7b9c8a',1,'CoverageControl::CoverageSystem']]],
  ['citation_6',['Citation',['../index.html#autotoc_md2',1,'']]],
  ['clairvoyant_5fcvt_2eh_7',['clairvoyant_cvt.h',['../clairvoyant__cvt_8h.html',1,'']]],
  ['clairvoyantcvt_8',['ClairvoyantCVT',['../classCoverageControl_1_1ClairvoyantCVT.html',1,'CoverageControl']]],
  ['compile_20and_20run_9',['Compile and Run',['../quick_start.html#autotoc_md24',1,'']]],
  ['computeactions_10',['ComputeActions',['../classCoverageControl_1_1AbstractController.html#af5bf5df992a8147d832f170e26a93e20',1,'CoverageControl::AbstractController::ComputeActions()'],['../classCoverageControl_1_1CentralizedCVT.html#a93324c1cb821ae58acecca65beda970f',1,'CoverageControl::CentralizedCVT::ComputeActions()'],['../classCoverageControl_1_1ClairvoyantCVT.html#a93324c1cb821ae58acecca65beda970f',1,'CoverageControl::ClairvoyantCVT::ComputeActions()'],['../classCoverageControl_1_1DecentralizedCVT.html#a93324c1cb821ae58acecca65beda970f',1,'CoverageControl::DecentralizedCVT::ComputeActions()'],['../classCoverageControl_1_1NearOptimalCVT.html#a93324c1cb821ae58acecca65beda970f',1,'CoverageControl::NearOptimalCVT::ComputeActions()'],['../classCoverageControl_1_1OracleBangExploreExploit.html#a93324c1cb821ae58acecca65beda970f',1,'CoverageControl::OracleBangExploreExploit::ComputeActions()'],['../classCoverageControl_1_1OracleExploreExploit.html#a93324c1cb821ae58acecca65beda970f',1,'CoverageControl::OracleExploreExploit::ComputeActions()']]],
  ['computeimportancerectangle_11',['ComputeImportanceRectangle',['../classCoverageControl_1_1WorldIDF.html#af913a85adce2dc93045e8754c13d8ba0',1,'CoverageControl::WorldIDF']]],
  ['computeoffsets_12',['ComputeOffsets',['../namespaceCoverageControl_1_1MapUtils.html#a74ee1b41afab01261eb3d6b55bc074c3',1,'CoverageControl::MapUtils']]],
  ['config_2eh_13',['config.h',['../config_8h.html',1,'']]],
  ['constants_14',['Constants',['../group__cpp__api__constants.html',1,'']]],
  ['constants_2eh_15',['constants.h',['../constants_8h.html',1,'']]],
  ['container_16',['Docker Container',['../installation.html#autotoc_md10',1,'']]],
  ['contributors_17',['Contributors',['../index.html#autotoc_md5',1,'']]],
  ['control_18',['Decentralized Coverage Control',['../coverage-control-problem.html#autotoc_md30',1,'']]],
  ['core_20api_19',['Core API',['../group__cpp__api.html',1,'']]],
  ['core_20library_20',['Building the Core Library',['../installation.html#autotoc_md17',1,'']]],
  ['cosangle_21',['CosAngle',['../classCoverageControl_1_1Vec2d.html#af6b42489d9e9fb4eab25ec578239e7dc',1,'CoverageControl::Vec2d']]],
  ['cost_20function_22',['Cost Function',['../coverage-control-problem.html#autotoc_md26',1,'']]],
  ['coverage_20control_23',['Decentralized Coverage Control',['../coverage-control-problem.html#autotoc_md30',1,'']]],
  ['coverage_5falgorithm_2ecpp_24',['coverage_algorithm.cpp',['../coverage__algorithm_8cpp.html',1,'']]],
  ['coverage_5fsystem_2ecpp_25',['coverage_system.cpp',['../coverage__system_8cpp.html',1,'']]],
  ['coverage_5fsystem_2eh_26',['coverage_system.h',['../coverage__system_8h.html',1,'']]],
  ['coveragecontrol_27',['CoverageControl',['../namespaceCoverageControl.html',1,'']]],
  ['coveragecontrol_3a_3amaputils_28',['MapUtils',['../namespaceCoverageControl_1_1MapUtils.html',1,'CoverageControl']]],
  ['coveragesystem_29',['CoverageSystem',['../classCoverageControl_1_1CoverageSystem.html',1,'CoverageSystem'],['../classCoverageControl_1_1CoverageSystem.html#a6d0fb1a19ee057e5d274e1b8fc9f9ea5',1,'CoverageControl::CoverageSystem::CoverageSystem()=delete'],['../classCoverageControl_1_1CoverageSystem.html#aa488e07158f6e2d9a663d6eaa0fc0d4d',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params)'],['../classCoverageControl_1_1CoverageSystem.html#ad241f1f0e345c4c3df964dcbf8fd6dd6',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params, int const num_gaussians, int const num_robots)'],['../classCoverageControl_1_1CoverageSystem.html#ab371d481cd2055d5a61bb003fd3230f7',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params, WorldIDF const &amp;world_idf, std::string const &amp;pos_file_name)'],['../classCoverageControl_1_1CoverageSystem.html#ae7b8ae7f16a57e4d99aad33989b722c7',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params, WorldIDF const &amp;world_idf, std::vector&lt; Point2 &gt; const &amp;robot_positions)'],['../classCoverageControl_1_1CoverageSystem.html#a5becb78ce3932fe865407f7d566dd2f5',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params, std::vector&lt; BivariateNormalDistribution &gt; const &amp;dists, std::vector&lt; Point2 &gt; const &amp;robot_positions)']]],
  ['cuda_20support_30',['CUDA Support',['../installation.html#autotoc_md15',1,'']]],
  ['cuda_5futils_2ecpp_31',['cuda_utils.cpp',['../cuda__utils_8cpp.html',1,'']]],
  ['cuda_5futils_2ecu_32',['cuda_utils.cu',['../cuda__utils_8cu.html',1,'']]],
  ['cuda_5futils_2eh_33',['cuda_utils.h',['../cuda__utils_8h.html',1,'']]],
  ['cudautils_34',['CudaUtils',['../classCoverageControl_1_1CudaUtils.html',1,'CudaUtils'],['../classCoverageControl_1_1CudaUtils.html#a2aed527243b8a3679189531fb6292c5c',1,'CoverageControl::CudaUtils::CudaUtils()']]]
];
