var searchData=
[
  ['c_20interface_0',['C++ Interface',['../quick_start.html#autotoc_md25',1,'']]],
  ['c_20library_1',['Building the Core C++ Library',['../installation.html#autotoc_md20',1,'']]],
  ['centralized_5fcvt_2eh_2',['centralized_cvt.h',['../centralized__cvt_8h.html',1,'']]],
  ['centralizedcvt_3',['CentralizedCVT',['../classCoverageControl_1_1CentralizedCVT.html',1,'CoverageControl']]],
  ['cgal_5fdelaunayhelper_4',['CGAL_DelaunayHelper',['../structCoverageControl_1_1CGAL__DelaunayHelper.html',1,'CoverageControl']]],
  ['challenge_5',['The Challenge',['../coverage-control-problem.html#autotoc_md41',1,'']]],
  ['checkoscillation_6',['CheckOscillation',['../classCoverageControl_1_1CoverageSystem.html#a845b117e1f5170f6b13c29737f7b9c8a',1,'CoverageControl::CoverageSystem']]],
  ['citation_7',['Citation',['../index.html#autotoc_md4',1,'']]],
  ['clairvoyant_5fcvt_2eh_8',['clairvoyant_cvt.h',['../clairvoyant__cvt_8h.html',1,'']]],
  ['clairvoyantcvt_9',['ClairvoyantCVT',['../classCoverageControl_1_1ClairvoyantCVT.html',1,'CoverageControl']]],
  ['cnn_10',['CNN',['../classcoverage__control_1_1nn_1_1models_1_1cnn_1_1CNN.html',1,'coverage_control::nn::models::cnn']]],
  ['cnnbackbone_11',['CNNBackBone',['../classcoverage__control_1_1nn_1_1models_1_1cnn__backbone_1_1CNNBackBone.html',1,'coverage_control::nn::models::cnn_backbone']]],
  ['cnnconfigparser_12',['CNNConfigParser',['../classcoverage__control_1_1nn_1_1models_1_1config__parser_1_1CNNConfigParser.html',1,'coverage_control::nn::models::config_parser']]],
  ['cnngnndataset_13',['CNNGNNDataset',['../classcoverage__control_1_1nn_1_1data__loaders_1_1loaders_1_1CNNGNNDataset.html',1,'coverage_control::nn::data_loaders::loaders']]],
  ['compile_20and_20run_14',['Compile and Run',['../quick_start.html#autotoc_md26',1,'']]],
  ['computeactions_15',['ComputeActions',['../classCoverageControl_1_1AbstractController.html#a4d5f88b1a902651a68857c8eeb8b31b7',1,'CoverageControl::AbstractController::ComputeActions()'],['../classCoverageControl_1_1CentralizedCVT.html#a1a841cad0973710964ae0bd8cf57cef7',1,'CoverageControl::CentralizedCVT::ComputeActions()'],['../classCoverageControl_1_1ClairvoyantCVT.html#a1a841cad0973710964ae0bd8cf57cef7',1,'CoverageControl::ClairvoyantCVT::ComputeActions()'],['../classCoverageControl_1_1DecentralizedCVT.html#a1a841cad0973710964ae0bd8cf57cef7',1,'CoverageControl::DecentralizedCVT::ComputeActions()'],['../classCoverageControl_1_1NearOptimalCVT.html#a1a841cad0973710964ae0bd8cf57cef7',1,'CoverageControl::NearOptimalCVT::ComputeActions()'],['../classCoverageControl_1_1OracleBangExploreExploit.html#a1a841cad0973710964ae0bd8cf57cef7',1,'CoverageControl::OracleBangExploreExploit::ComputeActions()'],['../classCoverageControl_1_1OracleExploreExploit.html#a1a841cad0973710964ae0bd8cf57cef7',1,'CoverageControl::OracleExploreExploit::ComputeActions()']]],
  ['computeoffsets_16',['ComputeOffsets',['../namespaceCoverageControl_1_1MapUtils.html#a74ee1b41afab01261eb3d6b55bc074c3',1,'CoverageControl::MapUtils']]],
  ['config_2eh_17',['config.h',['../config_8h.html',1,'']]],
  ['constants_18',['Constants',['../group__cpp__api__constants.html',1,'']]],
  ['constants_2eh_19',['constants.h',['../constants_8h.html',1,'']]],
  ['container_20',['Docker Container',['../installation.html#autotoc_md14',1,'']]],
  ['contributors_21',['Contributors',['../index.html#autotoc_md7',1,'']]],
  ['control_22',['Decentralized Coverage Control',['../coverage-control-problem.html#autotoc_md37',1,'']]],
  ['control_20problem_23',['Coverage Control Problem',['../coverage-control-problem.html#autotoc_md31',1,'']]],
  ['controller_24',['Controller',['../classeval__semantic__video_1_1Controller.html',1,'Controller'],['../classeval__video_1_1Controller.html',1,'Controller'],['../classsemantic__eval_1_1Controller.html',1,'Controller']]],
  ['controller_2epy_25',['controller.py',['../controller_8py.html',1,'']]],
  ['controllercvt_26',['ControllerCVT',['../classcontroller_1_1ControllerCVT.html',1,'controller']]],
  ['controllernn_27',['ControllerNN',['../classcontroller_1_1ControllerNN.html',1,'controller']]],
  ['core_20api_28',['Core API',['../group__cpp__api.html',1,'']]],
  ['core_20c_20library_29',['Building the Core C++ Library',['../installation.html#autotoc_md20',1,'']]],
  ['cosangle_30',['CosAngle',['../classCoverageControl_1_1Vec2d.html#af6b42489d9e9fb4eab25ec578239e7dc',1,'CoverageControl::Vec2d']]],
  ['cost_20function_31',['Cost Function',['../coverage-control-problem.html#autotoc_md33',1,'']]],
  ['coverage_20control_32',['Decentralized Coverage Control',['../coverage-control-problem.html#autotoc_md37',1,'']]],
  ['coverage_20control_20problem_33',['Coverage Control Problem',['../coverage-control-problem.html#autotoc_md31',1,'']]],
  ['coverage_5falgorithm_2ecpp_34',['coverage_algorithm.cpp',['../coverage__algorithm_8cpp.html',1,'']]],
  ['coverage_5fenv_5futils_2epy_35',['coverage_env_utils.py',['../coverage__env__utils_8py.html',1,'']]],
  ['coverage_5fsystem_2ecpp_36',['coverage_system.cpp',['../coverage__system_8cpp.html',1,'']]],
  ['coverage_5fsystem_2eh_37',['coverage_system.h',['../coverage__system_8h.html',1,'']]],
  ['coveragecontrol_38',['CoverageControl',['../namespaceCoverageControl.html',1,'']]],
  ['coveragecontrol_3a_3amaputils_39',['MapUtils',['../namespaceCoverageControl_1_1MapUtils.html',1,'CoverageControl']]],
  ['coverageenvutils_40',['CoverageEnvUtils',['../classcoverage__control_1_1nn_1_1data__loaders_1_1coverage__env__utils_1_1CoverageEnvUtils.html',1,'coverage_control::nn::data_loaders::coverage_env_utils']]],
  ['coveragesystem_41',['CoverageSystem',['../classCoverageControl_1_1CoverageSystem.html',1,'CoverageSystem'],['../classCoverageControl_1_1CoverageSystem.html#a6d0fb1a19ee057e5d274e1b8fc9f9ea5',1,'CoverageControl::CoverageSystem::CoverageSystem()=delete'],['../classCoverageControl_1_1CoverageSystem.html#aa488e07158f6e2d9a663d6eaa0fc0d4d',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params)'],['../classCoverageControl_1_1CoverageSystem.html#ad241f1f0e345c4c3df964dcbf8fd6dd6',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params, int const num_gaussians, int const num_robots)'],['../classCoverageControl_1_1CoverageSystem.html#ab371d481cd2055d5a61bb003fd3230f7',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params, WorldIDF const &amp;world_idf, std::string const &amp;pos_file_name)'],['../classCoverageControl_1_1CoverageSystem.html#ae7b8ae7f16a57e4d99aad33989b722c7',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params, WorldIDF const &amp;world_idf, std::vector&lt; Point2 &gt; const &amp;robot_positions)'],['../classCoverageControl_1_1CoverageSystem.html#a5becb78ce3932fe865407f7d566dd2f5',1,'CoverageControl::CoverageSystem::CoverageSystem(Parameters const &amp;params, std::vector&lt; BivariateNormalDistribution &gt; const &amp;dists, std::vector&lt; Point2 &gt; const &amp;robot_positions)']]],
  ['cuda_20support_42',['CUDA Support',['../installation.html#autotoc_md17',1,'']]],
  ['cuda_5futils_2ecpp_43',['cuda_utils.cpp',['../cuda__utils_8cpp.html',1,'']]],
  ['cuda_5futils_2ecu_44',['cuda_utils.cu',['../cuda__utils_8cu.html',1,'']]],
  ['cuda_5futils_2eh_45',['cuda_utils.h',['../cuda__utils_8h.html',1,'']]],
  ['cudautils_46',['CudaUtils',['../classCoverageControl_1_1CudaUtils.html',1,'CudaUtils'],['../classCoverageControl_1_1CudaUtils.html#a2aed527243b8a3679189531fb6292c5c',1,'CoverageControl::CudaUtils::CudaUtils()']]]
];
